version: '2'
services:
  keep2-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - 'discovery.type=single-node'
      - 'cluster.routing.allocation.disk.threshold_enabled=false'